DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS game;
DROP TABLE IF EXISTS songs;
DROP TABLE IF EXISTS cookies;

CREATE TABLE users (
    userid INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    passwd TEXT NOT NULL,
    isadmin BOOLEAN
);

CREATE TABLE game (
    userid INTEGER PRIMARY KEY,
    currscore INTEGER NOT NULL,
    currsong INTEGER NOT NULL,
    attempts INTEGER NOT NULL,
    used TEXT NOT NULL,
    highscore INTEGER NOT NULL
);

CREATE TABLE songs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    artist TEXT NOT NULL
);

CREATE TABLE cookies (
    sessionid TEXT UNIQUE NOT NULL,
    userid INTEGER UNIQUE NOT NULL,
    expiration INTEGER NOT NULL
);