DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS songs;
DROP TABLE IF EXISTS scores;
DROP TABLE IF EXISTS cookies;

CREATE TABLE users (
    userid INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    passwd TEXT NOT NULL,
    isadmin BOOLEAN
);

CREATE TABLE scores (
    userid INTEGER PRIMARY KEY AUTOINCREMENT,
    display TEXT,
    currscore INTEGER NOT NULL,
    highscore INTEGER NOT NULL
);

CREATE TABLE songs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    artist TEXT NOT NULL,
    title TEXT NOT NULL
);

CREATE TABLE cookies (
    sessionid TEXT UNIQUE NOT NULL,
    userid INTEGER UNIQUE NOT NULL,
    expiration INTEGER
);
